name: memes_life
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.0
  go_router: ^14.2.9
  google_fonts: ^6.2.1
  http: ^1.2.2
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.2
  in_app_update: ^4.2.3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4
  url_launcher: ^6.3.0
  image_cropper: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
